### ISSUE TITLE
pull request: added Kerbal mass to Command Chair option

### ISSUE THREAD

**Issue by mlheur** [linuxgurugamer/RCSBuildAid#7]
I forked your repo to https://github.com/mlheur/RCSBuildAid and made two changes: updated .version stuff for 1.4.3; and added a toggle for including Kerbonaut's mass in the Command Chair.  It works, I've done preliminary testing but haven't had time to be completely thorough.  The change is simple enough, I'm reasonably confident in it.

I'd submit this as a formal pull request but I've never done that with github before and I'm guessing my URL changes to the .version file, along my visual studio project file changes, you'll want to drop those from the code merge.  Also, for some reason my visual studio changed the whole MenuMass source file; even though it's just one Horizontal stanza added 5 lines at line 66.  I don't know which would be more work: merging my changes manually or doing the pull.

Feel free to take my changes, or not.  I'll pull mine down later to prevent clutter; I have no interest in providing long term support.  Let me know if there's anything else I should do.

**Comment by linuxgurugamer** [comment]
Thanks, and a piece of advice:

When you want to do a PR, you should only make changes to what is needed for the PR.  Changing the .version file  is useless and actually counterproductive, since you overwrite any local changes I have, and frankly, since I do the releases, I should be the one changing the revision.  You also changed the contents of the .version file, which is even worse.

You also shouldn't commit any changes to the VS project file, since that also overwrites my files.
It kind of looks like your VS changed spaces to tabs (or maybe back), maybe you changed the tabstops?
Regardless, i obviously can't do a PR.

I see changes to the following files:

Plugin/Settings.cs
Plugin/PartExtensions.cs
Plugin/GUI/MenuMass.cs

and you added this file:

mlheur.txt

I'll take a look and see if I can merge it by hand tomorrow.
Thanks

**Comment by linuxgurugamer** [comment]
I've merged this, you can remove yours.  I hope to get a release out soon
